### ISSUE TITLE
蓝本注册时出错

### ISSUE THREAD

**Issue by JoherYu** [greyli/flask-china#5]
在重写Albumy这个项目启动后，出现错误了TypeError: __ init __() got an unexpected keyword argument 'default'.下载源码之后，分别将源码根目录的__init__和blueprints目录下的main替换成我重新的文件后，替换__init__后源码能正常启动，但替换了main后就无法启动了。我检查了main后发现了几个错误，但改完后依然会报错。到底是哪里有问题？

---------------main--------------
```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os

from flask import Blueprint, request, current_app, render_template, flash, \
    abort, redirect, url_for, send_from_directory
from flask_login import current_user, login_required
from flask_dropzone import random_filename


from albumy.models import Photo, Follow, Tag, User, Notification, Comment, \
    Collect
from albumy.utils import redirect_back, resize_image
from albumy.extensions import db
from albumy.decorators import permission_required, confirm_required
from albumy.forms.main import CommentForm, DescriptionForm, TagForm
from albumy.notifications import push_comment_notification, push_collect_notification

from sqlalchemy.sql.expression import func

main_bp = Blueprint('main', __name__)

@main_bp.route('/')
def index():
    if current_user.is_authenticated:
        page = request.args.get('page', 1, type=int)
        per_page = current_app.config['ALBUMY_PHOTO_PER_PAGE']

        pagination = Photo.query.join(
            Follow, Follow.followed_id == Photo.author_id).filter(
            Follow.follower_id == current_user.id).order_by(
            Photo.timestamp.desc()).paginate(page, per_page)
        photos = pagination.items

    else:
        pagination = None
        photos = None

    tags = Tag.query.join(Tag.photos).group_by(Tag.id).order_by(
        func.count(Photo.id).desc()).limit(10)

    return render_template('main/index.html', pagination=pagination,
                           photos=photos, tags=tags)

```

-------------__init__-------------------------
```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os
import click

from flask import Flask, render_template
from flask_login import current_user

from albumy.settings import config
from albumy.models import Notification, Role

from albumy.blueprints.admin import admin_bp
from albumy.blueprints.user import user_bp
from albumy.blueprints.auth import auth_bp
from albumy.blueprints.main import main_bp
from albumy.blueprints.ajax import ajax_bp

from albumy.extensions import avatars, bootstrap, db, dropzone, csrf, \
    login_manager, mail, moment, whooshee

def create_app(config_name=None):
    if config_name is None:
        config_name = os.getenv('FLASK_ENV', 'development')

    app = Flask('albumy')

    app.config.from_object(config[config_name])

    register_extensions(app)
    register_blueprints(app)
    register_template_context(app)
    register_commands(app)
    register_errorhandlers(app)

    return app

def register_template_context(app):
    @app.context_processor
    def make_template_context():
        if current_user.is_authenticated:
            notification_count = Notification.query.with_parent(current_user).\
                filter_by(is_read=False).count
        else:
            notification_count = None
        return dict(notification_count=notification_count)

def register_blueprints(app):
    app.register_blueprint(main_bp)
    app.register_blueprint(user_bp, url_prefix='/user')
    app.register_blueprint(auth_bp, url_prefix='/auth')
    app.register_blueprint(admin_bp, url_prefix='/admin')
    app.register_blueprint(ajax_bp, url_prefix='/ajax')

def register_extensions(app):
    avatars.init_app(app)
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    dropzone.init_app(app)
    moment.init_app(app)
    whooshee.init_app(app)
    csrf.init_app(app)
```

```
Traceback (most recent call last)
File "c:\users\joher\.virtualenvs\social_network-yq2i3pci\lib\site-packages\flask\cli.py", line 76, in find_best_app
app = call_factory(script_info, app_factory)
File "c:\users\joher\.virtualenvs\social_network-yq2i3pci\lib\site-packages\flask\cli.py", line 116, in call_factory
return app_factory()
File "C:\Users\Joher\flask\social_network\albumy\__init__.py", line 31, in create_app
register_blueprints(app)
File "C:\Users\Joher\flask\social_network\albumy\__init__.py", line 49, in register_blueprints
app.register_blueprint(main_bp, url_prefix='/main')
File "c:\users\joher\.virtualenvs\social_network-yq2i3pci\lib\site-packages\flask\app.py", line 66, in wrapper_func
return f(self, *args, **kwargs)
File "c:\users\joher\.virtualenvs\social_network-yq2i3pci\lib\site-packages\flask\app.py", line 1115, in register_blueprint
blueprint.register(self, options, first_registration)
File "c:\users\joher\.virtualenvs\social_network-yq2i3pci\lib\site-packages\flask\blueprints.py", line 187, in register
deferred(state)
File "c:\users\joher\.virtualenvs\social_network-yq2i3pci\lib\site-packages\flask\blueprints.py", line 208, in <lambda>
s.add_url_rule(rule, endpoint, view_func, **options))
File "c:\users\joher\.virtualenvs\social_network-yq2i3pci\lib\site-packages\flask\blueprints.py", line 80, in add_url_rule
view_func, defaults=defaults, **options)
File "c:\users\joher\.virtualenvs\social_network-yq2i3pci\lib\site-packages\flask\app.py", line 66, in wrapper_func
return f(self, *args, **kwargs)
File "c:\users\joher\.virtualenvs\social_network-yq2i3pci\lib\site-packages\flask\app.py", line 1213, in add_url_rule
Open an interactive python shell in this framerule = self.url_rule_class(rule, methods=methods, **options)
TypeError: __init__() got an unexpected keyword argument 'default'
```

### 环境版本

* 操作系统：window 10
* Python：3.7
* Flask：1.0.2
[完整代码.txt](https://github.com/greyli/flask-china/files/2718265/default.txt)

**Comment by greyli** [comment]
找到下面这一行（或直接搜索 `default`）：
```py
@main_bp.route('/tag/<int:tag_id>', default={'order': 'by_time'})
```
把 `default` 改为 `defaults`。

**Comment by JoherYu** [comment]
> 找到下面这一行（或直接搜索 `default`）：
> 
> ```python
> @main_bp.route('/tag/<int:tag_id>', default={'order': 'by_time'})
> ```
> 
> 把 `default` 改为 `defaults`。

完美解决，我眼花了|(*′口`)，感谢
